name: panel_app
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - bleach=4.0.0
  - bokeh=2.3.3
  - bottleneck=1.3.2
  - brotlipy=0.7.0
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - cffi=1.14.0
  - charset-normalizer=2.0.4
  - cryptography=35.0.0
  - freetype=2.11.0
  - giflib=5.2.1
  - idna=3.2
  - importlib-metadata=4.8.1
  - intel-openmp=2021.4.0
  - jinja2=3.0.2
  - jpeg=9d
  - jupyter-panel-proxy
  - lcms2=2.12
  - libffi=3.2.1
  - libpng=1.6.37
  - libtiff=4.2.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - lz4-c=1.9.3
  - markdown=3.3.4
  - markupsafe=2.0.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - numexpr=2.7.3
  - numpy=1.21.2
  - numpy-base=1.21.2
  - olefile=0.46
  - openssl=1.1.1l
  - packaging=21.0
  - pandas=1.3.4
  - panel=0.12.1
  - param=1.11.1
  - pillow=8.4.0
  - pip=21.2.4
  - pycparser=2.20
  - pyct=0.4.8
  - pyopenssl=21.0.0
  - pyparsing=3.0.4
  - pysocks=1.7.1
  - python=3.8.2
  - python-dateutil=2.8.2
  - pytz=2021.3
  - pyviz_comms=2.0.2
  - pyyaml=6.0
  - readline=8.1
  - requests=2.26.0
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.11
  - tornado=6.1
  - tqdm=4.62.3
  - typing_extensions=3.10.0.2
  - urllib3=1.26.7
  - webencodings=0.5.1
  - wheel=0.37.0
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - cached-property==1.5.2
    - greenlet==1.1.2
    - ibis-framework==2.0.0
    - multipledispatch==0.6.0
    - parsy==1.3.0
    - regex==2021.11.10
    - sqlalchemy==1.4.26
    - toolz==0.11.2
